config/routes.rb
Rails.application.routes.draw do
  root to: 'static#index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :ulices
  resources :obszaries
  resources :restauracjes
  resources :typy_pracownikas
  resources :pracownicies
  resources :kliencis
  resources :zamowienias
  resources :produkties
  resources :produkty_na_zamowienius

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/klienci.rb
class Klienci < ApplicationRecord
  belongs_to :zamowienia

  has_secure_password

  validates :id_klienta, presence: true, uniqueness: true, length: { is: 6 }
  validates :imie, presence: true, uniqueness: true, length: { in: 3..10 }
  validates :nazwisko, presence: true, uniqueness: true, length: { in: 3..20 }
  validates :ulica, presence: true, uniqueness: true, length: { in: 3..30 }
  validates :kod_pocztowy, presence: true, uniqueness: true, length: { is: 6 }
  validates :numer_lokalu, presence: true, uniqueness: true, length: { in: 1..3 }
  validates :password, presence: true, length: { minimum: 6 }
end

app/models/obszary.rb
class Obszary < ApplicationRecord
  belongs_to :restauracje
  has_many :ulices
end

app/models/pracownicy.rb
class Pracownicy < ApplicationRecord
  belongs_to :zamowienia
  has_many :restauracjes
  has_many :typy_pracownikas
end

app/models/produkty.rb
class Produkty < ApplicationRecord
  belongs_to :produkty_na_zamowieniu
end

app/models/produkty_na_zamowieniu.rb
class ProduktyNaZamowieniu < ApplicationRecord
  has_many :produkties
  has_many :zamowienias
end

app/models/restauracje.rb
class Restauracje < ApplicationRecord
  belongs_to :pracownicy
  has_many :obszaries
end

app/models/typy_pracownika.rb
class TypyPracownika < ApplicationRecord
  belongs_to :pracownicy
end

app/models/ulice.rb
class Ulice < ApplicationRecord
  belongs_to :obszary
end

app/models/zamowienia.rb
class Zamowienia < ApplicationRecord
  belongs_to :produkty_na_zamowieniu
  has_many :pracownicies
  has_many :kliecis
end

app/controllers/restauracjes_controller.rb
class RestauracjesController < ApplicationController
  before_action :set_restauracje, only: [:show, :edit, :update, :destroy]

  # GET /restauracjes
  # GET /restauracjes.json
  def index
    @restauracjes = Restauracje.all
  end

  # GET /restauracjes/1
  # GET /restauracjes/1.json
  def show
  end

  # GET /restauracjes/new
  def new
    @restauracje = Restauracje.new
  end

  # GET /restauracjes/1/edit
  def edit
  end

  # POST /restauracjes
  # POST /restauracjes.json
  def create
    @restauracje = Restauracje.new(restauracje_params)

    respond_to do |format|
      if @restauracje.save
        format.html { redirect_to @restauracje, notice: 'Restauracje was successfully created.' }
        format.json { render :show, status: :created, location: @restauracje }
      else
        format.html { render :new }
        format.json { render json: @restauracje.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restauracjes/1
  # PATCH/PUT /restauracjes/1.json
  def update
    respond_to do |format|
      if @restauracje.update(restauracje_params)
        format.html { redirect_to @restauracje, notice: 'Restauracje was successfully updated.' }
        format.json { render :show, status: :ok, location: @restauracje }
      else
        format.html { render :edit }
        format.json { render json: @restauracje.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restauracjes/1
  # DELETE /restauracjes/1.json
  def destroy
    @restauracje.destroy
    respond_to do |format|
      format.html { redirect_to restauracjes_url, notice: 'Restauracje was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restauracje
      @restauracje = Restauracje.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restauracje_params
      params.require(:restauracje).permit(:id_restauracji, :nazwa, :ulica, :numer_lokalu, :kod_pocztowy, :pracownicy_id)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def index
      @restauracjas = Restauracje.all
      @kliencis = Klienci.all
    end
end

app/controllers/ulices_controller.rb
class UlicesController < ApplicationController
  before_action :set_ulice, only: [:show, :edit, :update, :destroy]

  # GET /ulices
  # GET /ulices.json
  def index
    @ulices = Ulice.all
  end

  # GET /ulices/1
  # GET /ulices/1.json
  def show
  end

  # GET /ulices/new
  def new
    @ulice = Ulice.new
  end

  # GET /ulices/1/edit
  def edit
  end

  # POST /ulices
  # POST /ulices.json
  def create
    @ulice = Ulice.new(ulice_params)

    respond_to do |format|
      if @ulice.save
        format.html { redirect_to @ulice, notice: 'Ulice was successfully created.' }
        format.json { render :show, status: :created, location: @ulice }
      else
        format.html { render :new }
        format.json { render json: @ulice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ulices/1
  # PATCH/PUT /ulices/1.json
  def update
    respond_to do |format|
      if @ulice.update(ulice_params)
        format.html { redirect_to @ulice, notice: 'Ulice was successfully updated.' }
        format.json { render :show, status: :ok, location: @ulice }
      else
        format.html { render :edit }
        format.json { render json: @ulice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ulices/1
  # DELETE /ulices/1.json
  def destroy
    @ulice.destroy
    respond_to do |format|
      format.html { redirect_to ulices_url, notice: 'Ulice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ulice
      @ulice = Ulice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ulice_params
      params.require(:ulice).permit(:id_ulicy, :ulica, :kod_pocztowy, :numer_lokalu, :obszary_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kliencis_helper.rb
module KliencisHelper
end

app/helpers/obszaries_helper.rb
module ObszariesHelper
end

app/helpers/pracownicies_helper.rb
module PracowniciesHelper
end

app/helpers/produkties_helper.rb
module ProduktiesHelper
end

app/helpers/restauracjes_helper.rb
module RestauracjesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(klient)
    session[:klient_id] = klient.id
  end
  def current_klient
    @current_klient ||= Klienci.find_by(id: session[:klient_id])
  end
  def logged_in?
      !current_klient.nil?
  end
  def log_out
    session.delete(:klient_id)
    @current_klient = nil
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/ulices_helper.rb
module UlicesHelper
end

app/helpers/zamowienias_helper.rb
module ZamowieniasHelper
end

app/views/restauracjes/_form.html.erb
<%= form_for(restauracje) do |f| %>
  <% if restauracje.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restauracje.errors.count, "error") %> prohibited this restauracje from being saved:</h2>

      <ul>
      <% restauracje.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_restauracji %>
    <%= f.number_field :id_restauracji %>
  </div>

  <div class="field">
    <%= f.label :nazwa %>
    <%= f.text_field :nazwa %>
  </div>

  <div class="field">
    <%= f.label :ulica %>
    <%= f.text_field :ulica %>
  </div>

  <div class="field">
    <%= f.label :numer_lokalu %>
    <%= f.text_field :numer_lokalu %>
  </div>

  <div class="field">
    <%= f.label :kod_pocztowy %>
    <%= f.text_field :kod_pocztowy %>
  </div>

  <div class="field">
    <%= f.label :pracownicy_id %>
    <%= f.text_field :pracownicy_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restauracjes/edit.html.erb
<h1>Editing Restauracje</h1>

<%= render 'form', restauracje: @restauracje %>

<%= link_to 'Show', @restauracje %> |
<%= link_to 'Back', restauracjes_path %>

app/views/restauracjes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restauracjes</h1>

<table>
  <thead>
    <tr>
      <th>Id restauracji</th>
      <th>Nazwa</th>
      <th>Ulica</th>
      <th>Numer lokalu</th>
      <th>Kod pocztowy</th>
      <th>Pracownicy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restauracjes.each do |restauracje| %>
      <tr>
        <td><%= restauracje.id_restauracji %></td>
        <td><%= restauracje.nazwa %></td>
        <td><%= restauracje.ulica %></td>
        <td><%= restauracje.numer_lokalu %></td>
        <td><%= restauracje.kod_pocztowy %></td>
        <td><%= restauracje.pracownicy %></td>
        <td><%= link_to 'Show', restauracje %></td>
        <td><%= link_to 'Edit', edit_restauracje_path(restauracje) %></td>
        <td><%= link_to 'Destroy', restauracje, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restauracje', new_restauracje_path %>

app/views/restauracjes/new.html.erb
<h1>New Restauracje</h1>

<%= render 'form', restauracje: @restauracje %>

<%= link_to 'Back', restauracjes_path %>

app/views/restauracjes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id restauracji:</strong>
  <%= @restauracje.id_restauracji %>
</p>

<p>
  <strong>Nazwa:</strong>
  <%= @restauracje.nazwa %>
</p>

<p>
  <strong>Ulica:</strong>
  <%= @restauracje.ulica %>
</p>

<p>
  <strong>Numer lokalu:</strong>
  <%= @restauracje.numer_lokalu %>
</p>

<p>
  <strong>Kod pocztowy:</strong>
  <%= @restauracje.kod_pocztowy %>
</p>

<p>
  <strong>Pracownicy:</strong>
  <%= @restauracje.pracownicy %>
</p>

<%= link_to 'Edit', edit_restauracje_path(@restauracje) %> |
<%= link_to 'Back', restauracjes_path %>