config/routes.rb
Rails.application.routes.draw do
  root to: 'static#index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :ulices
  resources :obszaries
  resources :restauracjes
  resources :typy_pracownikas
  resources :pracownicies
  resources :kliencis
  resources :zamowienias
  resources :produkties
  resources :produkty_na_zamowienius

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/klienci.rb
class Klienci < ApplicationRecord
  belongs_to :zamowienia

  has_secure_password

  validates :id_klienta, presence: true, uniqueness: true, length: { is: 6 }
  validates :imie, presence: true, uniqueness: true, length: { in: 3..10 }
  validates :nazwisko, presence: true, uniqueness: true, length: { in: 3..20 }
  validates :ulica, presence: true, uniqueness: true, length: { in: 3..30 }
  validates :kod_pocztowy, presence: true, uniqueness: true, length: { is: 6 }
  validates :numer_lokalu, presence: true, uniqueness: true, length: { in: 1..3 }
  validates :password, presence: true, length: { minimum: 6 }
end

app/models/obszary.rb
class Obszary < ApplicationRecord
  belongs_to :restauracje
  has_many :ulices
end

app/models/pracownicy.rb
class Pracownicy < ApplicationRecord
  belongs_to :zamowienia
  has_many :restauracjes
  has_many :typy_pracownikas
end

app/models/produkty.rb
class Produkty < ApplicationRecord
  belongs_to :produkty_na_zamowieniu
end

app/models/restauracje.rb
class Restauracje < ApplicationRecord
  belongs_to :pracownicy
  has_many :obszaries
end

app/models/typy_pracownika.rb
class TypyPracownika < ApplicationRecord
  belongs_to :pracownicy
end

app/models/ulice.rb
class Ulice < ApplicationRecord
  belongs_to :obszary
end

app/models/zamowienia.rb
class Zamowienia < ApplicationRecord
  belongs_to :produkty_na_zamowieniu
  has_many :pracownicies
  has_many :kliecis
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def index
      @restauracjas = Restauracje.all
      @kliencis = Klienci.all
    end
end

app/controllers/typy_pracownikas_controller.rb
class TypyPracownikasController < ApplicationController
  before_action :set_typy_pracownika, only: [:show, :edit, :update, :destroy]

  # GET /typy_pracownikas
  # GET /typy_pracownikas.json
  def index
    @typy_pracownikas = TypyPracownika.all
  end

  # GET /typy_pracownikas/1
  # GET /typy_pracownikas/1.json
  def show
  end

  # GET /typy_pracownikas/new
  def new
    @typy_pracownika = TypyPracownika.new
  end

  # GET /typy_pracownikas/1/edit
  def edit
  end

  # POST /typy_pracownikas
  # POST /typy_pracownikas.json
  def create
    @typy_pracownika = TypyPracownika.new(typy_pracownika_params)

    respond_to do |format|
      if @typy_pracownika.save
        format.html { redirect_to @typy_pracownika, notice: 'Typy pracownika was successfully created.' }
        format.json { render :show, status: :created, location: @typy_pracownika }
      else
        format.html { render :new }
        format.json { render json: @typy_pracownika.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /typy_pracownikas/1
  # PATCH/PUT /typy_pracownikas/1.json
  def update
    respond_to do |format|
      if @typy_pracownika.update(typy_pracownika_params)
        format.html { redirect_to @typy_pracownika, notice: 'Typy pracownika was successfully updated.' }
        format.json { render :show, status: :ok, location: @typy_pracownika }
      else
        format.html { render :edit }
        format.json { render json: @typy_pracownika.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /typy_pracownikas/1
  # DELETE /typy_pracownikas/1.json
  def destroy
    @typy_pracownika.destroy
    respond_to do |format|
      format.html { redirect_to typy_pracownikas_url, notice: 'Typy pracownika was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_typy_pracownika
      @typy_pracownika = TypyPracownika.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def typy_pracownika_params
      params.require(:typy_pracownika).permit(:id_typu, :nazwa_typu, :pracownicy_id)
    end
end

app/controllers/ulices_controller.rb
class UlicesController < ApplicationController
  before_action :set_ulice, only: [:show, :edit, :update, :destroy]

  # GET /ulices
  # GET /ulices.json
  def index
    @ulices = Ulice.all
  end

  # GET /ulices/1
  # GET /ulices/1.json
  def show
  end

  # GET /ulices/new
  def new
    @ulice = Ulice.new
  end

  # GET /ulices/1/edit
  def edit
  end

  # POST /ulices
  # POST /ulices.json
  def create
    @ulice = Ulice.new(ulice_params)

    respond_to do |format|
      if @ulice.save
        format.html { redirect_to @ulice, notice: 'Ulice was successfully created.' }
        format.json { render :show, status: :created, location: @ulice }
      else
        format.html { render :new }
        format.json { render json: @ulice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ulices/1
  # PATCH/PUT /ulices/1.json
  def update
    respond_to do |format|
      if @ulice.update(ulice_params)
        format.html { redirect_to @ulice, notice: 'Ulice was successfully updated.' }
        format.json { render :show, status: :ok, location: @ulice }
      else
        format.html { render :edit }
        format.json { render json: @ulice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ulices/1
  # DELETE /ulices/1.json
  def destroy
    @ulice.destroy
    respond_to do |format|
      format.html { redirect_to ulices_url, notice: 'Ulice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ulice
      @ulice = Ulice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ulice_params
      params.require(:ulice).permit(:id_ulicy, :ulica, :kod_pocztowy, :numer_lokalu, :obszary_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kliencis_helper.rb
module KliencisHelper
end

app/helpers/obszaries_helper.rb
module ObszariesHelper
end

app/helpers/pracownicies_helper.rb
module PracowniciesHelper
end

app/helpers/produkties_helper.rb
module ProduktiesHelper
end

app/helpers/restauracjes_helper.rb
module RestauracjesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(klient)
    session[:klient_id] = klient.id
  end
  def current_klient
    @current_klient ||= Klienci.find_by(id: session[:klient_id])
  end
  def logged_in?
      !current_klient.nil?
  end
  def log_out
    session.delete(:klient_id)
    @current_klient = nil
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/typy_pracownikas_helper.rb
module TypyPracownikasHelper
end

app/helpers/ulices_helper.rb
module UlicesHelper
end

app/helpers/zamowienias_helper.rb
module ZamowieniasHelper
end

app/views/typy_pracownikas/_form.html.erb
<%= form_for(typy_pracownika) do |f| %>
  <% if typy_pracownika.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(typy_pracownika.errors.count, "error") %> prohibited this typy_pracownika from being saved:</h2>

      <ul>
      <% typy_pracownika.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_typu %>
    <%= f.number_field :id_typu %>
  </div>

  <div class="field">
    <%= f.label :nazwa_typu %>
    <%= f.text_field :nazwa_typu %>
  </div>

  <div class="field">
    <%= f.label :pracownicy_id %>
    <%= f.text_field :pracownicy_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/typy_pracownikas/edit.html.erb
<h1>Editing Typy Pracownika</h1>

<%= render 'form', typy_pracownika: @typy_pracownika %>

<%= link_to 'Show', @typy_pracownika %> |
<%= link_to 'Back', typy_pracownikas_path %>

app/views/typy_pracownikas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Typy Pracownikas</h1>

<table>
  <thead>
    <tr>
      <th>Id typu</th>
      <th>Nazwa typu</th>
      <th>Pracownicy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @typy_pracownikas.each do |typy_pracownika| %>
      <tr>
        <td><%= typy_pracownika.id_typu %></td>
        <td><%= typy_pracownika.nazwa_typu %></td>
        <td><%= typy_pracownika.pracownicy %></td>
        <td><%= link_to 'Show', typy_pracownika %></td>
        <td><%= link_to 'Edit', edit_typy_pracownika_path(typy_pracownika) %></td>
        <td><%= link_to 'Destroy', typy_pracownika, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Typy Pracownika', new_typy_pracownika_path %>

app/views/typy_pracownikas/new.html.erb
<h1>New Typy Pracownika</h1>

<%= render 'form', typy_pracownika: @typy_pracownika %>

<%= link_to 'Back', typy_pracownikas_path %>

app/views/typy_pracownikas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id typu:</strong>
  <%= @typy_pracownika.id_typu %>
</p>

<p>
  <strong>Nazwa typu:</strong>
  <%= @typy_pracownika.nazwa_typu %>
</p>

<p>
  <strong>Pracownicy:</strong>
  <%= @typy_pracownika.pracownicy %>
</p>

<%= link_to 'Edit', edit_typy_pracownika_path(@typy_pracownika) %> |
<%= link_to 'Back', typy_pracownikas_path %>