config/routes.rb
Rails.application.routes.draw do
  root to: 'static#index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :ulices
  resources :obszaries
  resources :restauracjes
  resources :typy_pracownikas
  resources :pracownicies
  resources :kliencis
  resources :zamowienias
  resources :produkties
  resources :produkty_na_zamowienius

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/klienci.rb
class Klienci < ApplicationRecord
  belongs_to :zamowienia

  has_secure_password

  validates :id_klienta, presence: true, uniqueness: true, length: { is: 6 }
  validates :imie, presence: true, uniqueness: true, length: { in: 3..10 }
  validates :nazwisko, presence: true, uniqueness: true, length: { in: 3..20 }
  validates :ulica, presence: true, uniqueness: true, length: { in: 3..30 }
  validates :kod_pocztowy, presence: true, uniqueness: true, length: { is: 6 }
  validates :numer_lokalu, presence: true, uniqueness: true, length: { in: 1..3 }
  validates :password, presence: true, length: { minimum: 6 }
end

app/models/obszary.rb
class Obszary < ApplicationRecord
  belongs_to :restauracje
  has_many :ulices
end

app/models/pracownicy.rb
class Pracownicy < ApplicationRecord
  belongs_to :zamowienia
  has_many :restauracjes
  has_many :typy_pracownikas
end

app/models/produkty.rb
class Produkty < ApplicationRecord
  belongs_to :produkty_na_zamowieniu
end

app/models/produkty_na_zamowieniu.rb
class ProduktyNaZamowieniu < ApplicationRecord
  has_many :produkties
  has_many :zamowienias
end

app/models/restauracje.rb
class Restauracje < ApplicationRecord
  belongs_to :pracownicy
  has_many :obszaries
end

app/models/typy_pracownika.rb
class TypyPracownika < ApplicationRecord
  belongs_to :pracownicy
end

app/models/ulice.rb
class Ulice < ApplicationRecord
  belongs_to :obszary
end

app/models/zamowienia.rb
class Zamowienia < ApplicationRecord
  belongs_to :produkty_na_zamowieniu
  has_many :pracownicies
  has_many :kliecis
end

app/controllers/kliencis_controller.rb
class KliencisController < ApplicationController
  before_action :set_klienci, only: [:show, :edit, :update, :destroy]

  # GET /kliencis
  # GET /kliencis.json
  def index
    @kliencis = Klienci.all
  end

  # GET /kliencis/1
  # GET /kliencis/1.json
  def show
  end

  # GET /kliencis/new
  def new
    @klienci = Klienci.new
  end

  # GET /kliencis/1/edit
  def edit
  end

  # POST /kliencis
  # POST /kliencis.json
  def create
    @klienci = Klienci.new(klienci_params)

    respond_to do |format|
      if @klienci.save
        format.html { redirect_to @klienci, notice: 'Klienci was successfully created.' }
        format.json { render :show, status: :created, location: @klienci }
      else
        format.html { render :new }
        format.json { render json: @klienci.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kliencis/1
  # PATCH/PUT /kliencis/1.json
  def update
    respond_to do |format|
      if @klienci.update(klienci_params)
        format.html { redirect_to @klienci, notice: 'Klienci was successfully updated.' }
        format.json { render :show, status: :ok, location: @klienci }
      else
        format.html { render :edit }
        format.json { render json: @klienci.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kliencis/1
  # DELETE /kliencis/1.json
  def destroy
    @klienci.destroy
    respond_to do |format|
      format.html { redirect_to kliencis_url, notice: 'Klienci was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_klienci
      @klienci = Klienci.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def klienci_params
      params.require(:klienci).permit(:id_klienta, :imie, :nazwisko, :ulica, :kod_pocztowy, :numer_lokalu, :zamowienia_id, :password, :password_confirmation)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def index
      @restauracjas = Restauracje.all
      @kliencis = Klienci.all
    end
end

app/controllers/ulices_controller.rb
class UlicesController < ApplicationController
  before_action :set_ulice, only: [:show, :edit, :update, :destroy]

  # GET /ulices
  # GET /ulices.json
  def index
    @ulices = Ulice.all
  end

  # GET /ulices/1
  # GET /ulices/1.json
  def show
  end

  # GET /ulices/new
  def new
    @ulice = Ulice.new
  end

  # GET /ulices/1/edit
  def edit
  end

  # POST /ulices
  # POST /ulices.json
  def create
    @ulice = Ulice.new(ulice_params)

    respond_to do |format|
      if @ulice.save
        format.html { redirect_to @ulice, notice: 'Ulice was successfully created.' }
        format.json { render :show, status: :created, location: @ulice }
      else
        format.html { render :new }
        format.json { render json: @ulice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ulices/1
  # PATCH/PUT /ulices/1.json
  def update
    respond_to do |format|
      if @ulice.update(ulice_params)
        format.html { redirect_to @ulice, notice: 'Ulice was successfully updated.' }
        format.json { render :show, status: :ok, location: @ulice }
      else
        format.html { render :edit }
        format.json { render json: @ulice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ulices/1
  # DELETE /ulices/1.json
  def destroy
    @ulice.destroy
    respond_to do |format|
      format.html { redirect_to ulices_url, notice: 'Ulice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ulice
      @ulice = Ulice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ulice_params
      params.require(:ulice).permit(:id_ulicy, :ulica, :kod_pocztowy, :numer_lokalu, :obszary_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kliencis_helper.rb
module KliencisHelper
end

app/helpers/obszaries_helper.rb
module ObszariesHelper
end

app/helpers/pracownicies_helper.rb
module PracowniciesHelper
end

app/helpers/produkties_helper.rb
module ProduktiesHelper
end

app/helpers/restauracjes_helper.rb
module RestauracjesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(klient)
    session[:klient_id] = klient.id
  end
  def current_klient
    @current_klient ||= Klienci.find_by(id: session[:klient_id])
  end
  def logged_in?
      !current_klient.nil?
  end
  def log_out
    session.delete(:klient_id)
    @current_klient = nil
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/ulices_helper.rb
module UlicesHelper
end

app/helpers/zamowienias_helper.rb
module ZamowieniasHelper
end

app/views/kliencis/_form.html.erb
<%= form_for(klienci) do |f| %>
  <% if klienci.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(klienci.errors.count, "error") %> prohibited this klienci from being saved:</h2>

      <ul>
      <% klienci.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_klienta %>
    <%= f.number_field :id_klienta %>
  </div>

  <div class="field
    <%= f.label :password %>
    <%= f.password_field :password, id: :klient_password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, id: :klient_password_confirmation %>
  </div>

  <div class="field">
    <%= f.label :imie %>
    <%= f.text_field :imie %>
  </div>

  <div class="field">
    <%= f.label :nazwisko %>
    <%= f.text_field :nazwisko %>
  </div>

  <div class="field">
    <%= f.label :ulica %>
    <%= f.text_field :ulica %>
  </div>

  <div class="field">
    <%= f.label :kod_pocztowy %>
    <%= f.text_field :kod_pocztowy %>
  </div>

  <div class="field">
    <%= f.label :numer_lokalu %>
    <%= f.text_field :numer_lokalu %>
  </div>

  <div class="field">
    <%= f.label :zamowienia_id %>
    <%= f.text_field :zamowienia_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kliencis/edit.html.erb
<h1>Editing Klienci</h1>

<%= render 'form', klienci: @klienci %>

<%= link_to 'Show', @klienci %> |
<%= link_to 'Back', kliencis_path %>

app/views/kliencis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Kliencis</h1>

<table>
  <thead>
    <tr>
      <th>Id klienta</th>
      <th>Imie</th>
      <th>Nazwisko</th>
      <th>Ulica</th>
      <th>Kod pocztowy</th>
      <th>Numer lokalu</th>
      <th>Zamowienia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kliencis.each do |klienci| %>
      <tr>
        <td><%= klienci.id_klienta %></td>
        <td><%= klienci.imie %></td>
        <td><%= klienci.nazwisko %></td>
        <td><%= klienci.ulica %></td>
        <td><%= klienci.kod_pocztowy %></td>
        <td><%= klienci.numer_lokalu %></td>
        <td><%= klienci.zamowienia %></td>
        <td><%= link_to 'Show', klienci %></td>
        <td><%= link_to 'Edit', edit_klienci_path(klienci) %></td>
        <td><%= link_to 'Destroy', klienci, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Klienci', new_klienci_path %>

app/views/kliencis/new.html.erb
<h1>New Klienci</h1>

<%= render 'form', klienci: @klienci %>

<%= link_to 'Back', kliencis_path %>

app/views/kliencis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id klienta:</strong>
  <%= @klienci.id_klienta %>
</p>

<p>
  <strong>Imie:</strong>
  <%= @klienci.imie %>
</p>

<p>
  <strong>Nazwisko:</strong>
  <%= @klienci.nazwisko %>
</p>

<p>
  <strong>Ulica:</strong>
  <%= @klienci.ulica %>
</p>

<p>
  <strong>Kod pocztowy:</strong>
  <%= @klienci.kod_pocztowy %>
</p>

<p>
  <strong>Numer lokalu:</strong>
  <%= @klienci.numer_lokalu %>
</p>

<p>
  <strong>Zamowienia:</strong>
  <%= @klienci.zamowienia %>
</p>

<%= link_to 'Edit', edit_klienci_path(@klienci) %> |
<%= link_to 'Back', kliencis_path %>

app/views/ulices/_form.html.erb
<%= form_for(ulice) do |f| %>
  <% if ulice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ulice.errors.count, "error") %> prohibited this ulice from being saved:</h2>

      <ul>
      <% ulice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_ulicy %>
    <%= f.number_field :id_ulicy %>
  </div>

  <div class="field">
    <%= f.label :ulica %>
    <%= f.text_field :ulica %>
  </div>

  <div class="field">
    <%= f.label :kod_pocztowy %>
    <%= f.text_field :kod_pocztowy %>
  </div>

  <div class="field">
    <%= f.label :numer_lokalu %>
    <%= f.text_field :numer_lokalu %>
  </div>

  <div class="field">
    <%= f.label :obszary_id %>
    <%= f.text_field :obszary_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ulices/edit.html.erb
<h1>Editing Ulice</h1>

<%= render 'form', ulice: @ulice %>

<%= link_to 'Show', @ulice %> |
<%= link_to 'Back', ulices_path %>

app/views/ulices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ulices</h1>

<table>
  <thead>
    <tr>
      <th>Id ulicy</th>
      <th>Ulica</th>
      <th>Kod pocztowy</th>
      <th>Numer lokalu</th>
      <th>Obszary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ulices.each do |ulice| %>
      <tr>
        <td><%= ulice.id_ulicy %></td>
        <td><%= ulice.ulica %></td>
        <td><%= ulice.kod_pocztowy %></td>
        <td><%= ulice.numer_lokalu %></td>
        <td><%= ulice.obszary %></td>
        <td><%= link_to 'Show', ulice %></td>
        <td><%= link_to 'Edit', edit_ulice_path(ulice) %></td>
        <td><%= link_to 'Destroy', ulice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ulice', new_ulice_path %>

app/views/ulices/new.html.erb
<h1>New Ulice</h1>

<%= render 'form', ulice: @ulice %>

<%= link_to 'Back', ulices_path %>

app/views/ulices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id ulicy:</strong>
  <%= @ulice.id_ulicy %>
</p>

<p>
  <strong>Ulica:</strong>
  <%= @ulice.ulica %>
</p>

<p>
  <strong>Kod pocztowy:</strong>
  <%= @ulice.kod_pocztowy %>
</p>

<p>
  <strong>Numer lokalu:</strong>
  <%= @ulice.numer_lokalu %>
</p>

<p>
  <strong>Obszary:</strong>
  <%= @ulice.obszary %>
</p>

<%= link_to 'Edit', edit_ulice_path(@ulice) %> |
<%= link_to 'Back', ulices_path %>