config/routes.rb
Rails.application.routes.draw do
  root to: 'static#index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :ulices
  resources :obszaries
  resources :restauracjes
  resources :typy_pracownikas
  resources :pracownicies
  resources :kliencis
  resources :zamowienias
  resources :produkties
  resources :produkty_na_zamowienius

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/klienci.rb
class Klienci < ApplicationRecord
  belongs_to :zamowienia

  has_secure_password

  validates :id_klienta, presence: true, uniqueness: true, length: { is: 6 }
  validates :imie, presence: true, uniqueness: true, length: { in: 3..10 }
  validates :nazwisko, presence: true, uniqueness: true, length: { in: 3..20 }
  validates :ulica, presence: true, uniqueness: true, length: { in: 3..30 }
  validates :kod_pocztowy, presence: true, uniqueness: true, length: { is: 6 }
  validates :numer_lokalu, presence: true, uniqueness: true, length: { in: 1..3 }
  validates :password, presence: true, length: { minimum: 6 }
end

app/models/obszary.rb
class Obszary < ApplicationRecord
  belongs_to :restauracje
  has_many :ulices
end

app/models/pracownicy.rb
class Pracownicy < ApplicationRecord
  belongs_to :zamowienia
  has_many :restauracjes
  has_many :typy_pracownikas
end

app/models/produkty.rb
class Produkty < ApplicationRecord
  belongs_to :produkty_na_zamowieniu
end

app/models/produkty_na_zamowieniu.rb
class ProduktyNaZamowieniu < ApplicationRecord
  has_many :produkties
  has_many :zamowienias
end

app/models/restauracje.rb
class Restauracje < ApplicationRecord
  belongs_to :pracownicy
  has_many :obszaries
end

app/models/typy_pracownika.rb
class TypyPracownika < ApplicationRecord
  belongs_to :pracownicy
end

app/models/ulice.rb
class Ulice < ApplicationRecord
  belongs_to :obszary
end

app/models/zamowienia.rb
class Zamowienia < ApplicationRecord
  belongs_to :produkty_na_zamowieniu
  has_many :pracownicies
  has_many :kliecis
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def index
      @restauracjas = Restauracje.all
      @kliencis = Klienci.all
    end
end

app/controllers/ulices_controller.rb
class UlicesController < ApplicationController
  before_action :set_ulice, only: [:show, :edit, :update, :destroy]

  # GET /ulices
  # GET /ulices.json
  def index
    @ulices = Ulice.all
  end

  # GET /ulices/1
  # GET /ulices/1.json
  def show
  end

  # GET /ulices/new
  def new
    @ulice = Ulice.new
  end

  # GET /ulices/1/edit
  def edit
  end

  # POST /ulices
  # POST /ulices.json
  def create
    @ulice = Ulice.new(ulice_params)

    respond_to do |format|
      if @ulice.save
        format.html { redirect_to @ulice, notice: 'Ulice was successfully created.' }
        format.json { render :show, status: :created, location: @ulice }
      else
        format.html { render :new }
        format.json { render json: @ulice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ulices/1
  # PATCH/PUT /ulices/1.json
  def update
    respond_to do |format|
      if @ulice.update(ulice_params)
        format.html { redirect_to @ulice, notice: 'Ulice was successfully updated.' }
        format.json { render :show, status: :ok, location: @ulice }
      else
        format.html { render :edit }
        format.json { render json: @ulice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ulices/1
  # DELETE /ulices/1.json
  def destroy
    @ulice.destroy
    respond_to do |format|
      format.html { redirect_to ulices_url, notice: 'Ulice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ulice
      @ulice = Ulice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ulice_params
      params.require(:ulice).permit(:id_ulicy, :ulica, :kod_pocztowy, :numer_lokalu, :obszary_id)
    end
end

app/controllers/zamowienias_controller.rb
class ZamowieniasController < ApplicationController
  before_action :set_zamowienia, only: [:show, :edit, :update, :destroy]

  # GET /zamowienias
  # GET /zamowienias.json
  def index
    @zamowienias = Zamowienia.all
  end

  # GET /zamowienias/1
  # GET /zamowienias/1.json
  def show
  end

  # GET /zamowienias/new
  def new
    @zamowienia = Zamowienia.new
  end

  # GET /zamowienias/1/edit
  def edit
  end

  # POST /zamowienias
  # POST /zamowienias.json
  def create
    @zamowienia = Zamowienia.new(zamowienia_params)

    respond_to do |format|
      if @zamowienia.save
        format.html { redirect_to @zamowienia, notice: 'Zamowienia was successfully created.' }
        format.json { render :show, status: :created, location: @zamowienia }
      else
        format.html { render :new }
        format.json { render json: @zamowienia.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zamowienias/1
  # PATCH/PUT /zamowienias/1.json
  def update
    respond_to do |format|
      if @zamowienia.update(zamowienia_params)
        format.html { redirect_to @zamowienia, notice: 'Zamowienia was successfully updated.' }
        format.json { render :show, status: :ok, location: @zamowienia }
      else
        format.html { render :edit }
        format.json { render json: @zamowienia.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zamowienias/1
  # DELETE /zamowienias/1.json
  def destroy
    @zamowienia.destroy
    respond_to do |format|
      format.html { redirect_to zamowienias_url, notice: 'Zamowienia was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zamowienia
      @zamowienia = Zamowienia.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zamowienia_params
      params.require(:zamowienia).permit(:id_zamowienia, :czas_realizacji, :produkty_na_zamowieniu_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kliencis_helper.rb
module KliencisHelper
end

app/helpers/obszaries_helper.rb
module ObszariesHelper
end

app/helpers/pracownicies_helper.rb
module PracowniciesHelper
end

app/helpers/produkties_helper.rb
module ProduktiesHelper
end

app/helpers/restauracjes_helper.rb
module RestauracjesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(klient)
    session[:klient_id] = klient.id
  end
  def current_klient
    @current_klient ||= Klienci.find_by(id: session[:klient_id])
  end
  def logged_in?
      !current_klient.nil?
  end
  def log_out
    session.delete(:klient_id)
    @current_klient = nil
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/ulices_helper.rb
module UlicesHelper
end

app/helpers/zamowienias_helper.rb
module ZamowieniasHelper
end

app/views/zamowienias/_form.html.erb
<%= form_for(zamowienia) do |f| %>
  <% if zamowienia.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(zamowienia.errors.count, "error") %> prohibited this zamowienia from being saved:</h2>

      <ul>
      <% zamowienia.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_zamowienia %>
    <%= f.number_field :id_zamowienia %>
  </div>

  <div class="field">
    <%= f.label :czas_realizacji %>
    <%= f.number_field :czas_realizacji %>
  </div>

  <div class="field">
    <%= f.label :produkty_na_zamowieniu_id %>
    <%= f.text_field :produkty_na_zamowieniu_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zamowienias/edit.html.erb
<h1>Editing Zamowienia</h1>

<%= render 'form', zamowienia: @zamowienia %>

<%= link_to 'Show', @zamowienia %> |
<%= link_to 'Back', zamowienias_path %>

app/views/zamowienias/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Zamowienias</h1>

<table>
  <thead>
    <tr>
      <th>Id zamowienia</th>
      <th>Czas realizacji</th>
      <th>Produkty na zamowieniu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @zamowienias.each do |zamowienia| %>
      <tr>
        <td><%= zamowienia.id_zamowienia %></td>
        <td><%= zamowienia.czas_realizacji %></td>
        <td><%= zamowienia.produkty_na_zamowieniu %></td>
        <td><%= link_to 'Show', zamowienia %></td>
        <td><%= link_to 'Edit', edit_zamowienia_path(zamowienia) %></td>
        <td><%= link_to 'Destroy', zamowienia, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zamowienia', new_zamowienia_path %>

app/views/zamowienias/new.html.erb
<h1>New Zamowienia</h1>

<%= render 'form', zamowienia: @zamowienia %>

<%= link_to 'Back', zamowienias_path %>

app/views/zamowienias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id zamowienia:</strong>
  <%= @zamowienia.id_zamowienia %>
</p>

<p>
  <strong>Czas realizacji:</strong>
  <%= @zamowienia.czas_realizacji %>
</p>

<p>
  <strong>Produkty na zamowieniu:</strong>
  <%= @zamowienia.produkty_na_zamowieniu %>
</p>

<%= link_to 'Edit', edit_zamowienia_path(@zamowienia) %> |
<%= link_to 'Back', zamowienias_path %>